version: '3.7'

services:
    frontend:
        container_name: tamerun
        stdin_open: true
        tty: true
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - '.:/app'
            - '/app/node_modules'
        ports:
            - '443:5173'
            - '24678:24678'
        environment:
            - CHOKIDAR_USEPOLLING=true
