version: '3.7'

services:
    frontend:
        container_name: tamerun
        stdin_open: true
        tty: true
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '0.0.0.0:5173:5173'
        networks:
            - tamerunnet
        depends_on:
            - backend
        restart: always

    backend:
        container_name: tamerun_server
        stdin_open: true
        build:
            context: ./backend
            dockerfile: Dockerfile
        ports:
            - '0.0.0.0:5000:5000'
        networks:
            - tamerunnet
        restart: always

    nginx-router:
        container_name: tamerun_nginx
        stdin_open: true
        build:
            context: ./nginx-router
            dockerfile: Dockerfile
        ports:
            - '0.0.0.0:443:443'
            - '0.0.0.0:80:80'
        networks:
            - tamerunnet
        depends_on:
            - backend
            - frontend
        volumes:
            - ./certbot/conf:/etc/letsencrypt    # Смонтированные SSL сертификаты
            - ./certbot/www:/var/www/certbot     # Директория для HTTP-01 challenge
        restart: always

    certbot:
        image: certbot/certbot
        container_name: certbot
        volumes:
            - ./certbot/conf:/etc/letsencrypt    # Монтируем те же сертификаты, что и Nginx
            - ./certbot/www:/var/www/certbot     # Монтируем ту же директорию для challenge
        networks:
            - tamerunnet
        command: >
            ["certbot", "certonly",
            "--webroot", "-w", "/var/www/certbot",
            "-d", "tamerun-invest.ru",
            "-d", "www.tamerun-invest.ru",
            "--email", "sap@grad1.ru",
            "--agree-tos",
            "--no-eff-email",
            "--staging"]


networks:
    tamerunnet:
        name: tamerun_network
        driver: bridge
